//
//  VerbsBank.swift
//  quizzVerbs
//
//  Created by misael rivera on 27/05/18.
//  Copyright © 2018 misael rivera. All rights reserved.
//

import Foundation
struct VerbsBank {
    var verbsList = [Verbs]()
    init() {
        verbsList.append(Verbs(verb: "bear", answer: "borne", translation: "Llevar"))
        verbsList.append(Verbs(verb: "be", answer: "been",translation: "Ser/estar"))
        verbsList.append(Verbs(verb: "beat", answer: "beaten",translation: "Golpear"))
        verbsList.append(Verbs(verb: "bet", answer: "bet",translation: "Apostar"))
        verbsList.append(Verbs(verb: "bite", answer: "bitten",translation: "Morder"))
        verbsList.append(Verbs(verb: "blow", answer: "blown",translation: "Soplar/esplotar"))
        verbsList.append(Verbs(verb: "broadcast", answer: "broadcast",translation: "Transmitir"))
        verbsList.append(Verbs(verb: "burn", answer: "burnt",translation: "Quemar"))
        verbsList.append(Verbs(verb: "buy", answer: "bought",translation: "Comprar"))
        verbsList.append(Verbs(verb: "become", answer: "become",translation: "transformar"))
        verbsList.append(Verbs(verb: "begin", answer: "begun",translation: "Empezar"))
        verbsList.append(Verbs(verb: "break", answer: "broken",translation: "Romper"))
        verbsList.append(Verbs(verb: "bring", answer: "brought",translation: "Traer"))
        verbsList.append(Verbs(verb: "build", answer: "built",translation: "Construir"))
        verbsList.append(Verbs(verb: "catch", answer: "caught",translation: "Atrapar"))
        verbsList.append(Verbs(verb: "choose", answer: "chosen",translation: "Escoger"))
        verbsList.append(Verbs(verb: "come", answer: "come",translation: "Venir"))
        verbsList.append(Verbs(verb: "cost", answer: "cost",translation: "Costar"))
        verbsList.append(Verbs(verb: "cut", answer: "cut",translation: "Cortar"))
        verbsList.append(Verbs(verb: "do", answer: "done",translation: "Hacer"))
        verbsList.append(Verbs(verb: "do", answer: "done",translation: "Hacer"))
        verbsList.append(Verbs(verb: "draw", answer: "drawn",translation: "Dibujar"))
        verbsList.append(Verbs(verb: "dream", answer: "dreamt",translation: "Soñar"))
        verbsList.append(Verbs(verb: "drink", answer: "drunk",translation: "Beber"))
        verbsList.append(Verbs(verb: "drive", answer: "driven",translation: "Manejar"))
        verbsList.append(Verbs(verb: "dye", answer: "dyed",translation: "Teñir"))
        verbsList.append(Verbs(verb: "eat", answer: "eaten",translation: "Comer"))
        verbsList.append(Verbs(verb: "fall", answer: "fallen",translation: "Caer"))
        verbsList.append(Verbs(verb: "feed", answer: "fed",translation: "Alimentar"))
        verbsList.append(Verbs(verb: "fight", answer: "fought",translation: "Pelear"))
        verbsList.append(Verbs(verb: "find", answer: "found",translation: "Encontrar"))
        verbsList.append(Verbs(verb: "fly", answer: "flown",translation: "Volar"))
        verbsList.append(Verbs(verb: "forget", answer: "forgotten",translation: "Olvidar"))
        verbsList.append(Verbs(verb: "freeze", answer: "frozen",translation: "Congelar"))
        verbsList.append(Verbs(verb: "get", answer: "got",translation: "Obtener"))
        verbsList.append(Verbs(verb: "give", answer: "given",translation: "Dar"))
        verbsList.append(Verbs(verb: "go", answer: "gone",translation: "Ir"))
        verbsList.append(Verbs(verb: "grow", answer: "grown",translation: "Crecer"))
        verbsList.append(Verbs(verb: "hang", answer: "hung",translation: "Colgar"))
        verbsList.append(Verbs(verb: "have", answer: "had",translation: "Tener"))
        verbsList.append(Verbs(verb: "hear", answer: "heard",translation: "Escuchar"))
        verbsList.append(Verbs(verb: "hide", answer: "hidden",translation: "Esconder"))
        verbsList.append(Verbs(verb: "hit", answer: "hit",translation: "Golpear"))
        verbsList.append(Verbs(verb: "hold", answer: "held",translation: "Sostener"))
        verbsList.append(Verbs(verb: "hurt", answer: "hurt",translation: "Herir"))
        verbsList.append(Verbs(verb: "keep", answer: "kept",translation: "Mantener"))
        verbsList.append(Verbs(verb: "extinguish", answer: "extinguished",translation: "Extinguir"))
        /*verbsList.append(Verbs(verb: "bear", answer: "born", translation: "aqui va"))
        verbsList.append(Verbs(verb: "be", answer: "been",translation: "aqui va"))
        verbsList.append(Verbs(verb: "beat", answer: "beaten",translation: "aqui va"))
        verbsList.append(Verbs(verb: "bet", answer: "bet",translation: "aqui va"))
        verbsList.append(Verbs(verb: "bite", answer: "bitten",translation: "aqui va"))
        verbsList.append(Verbs(verb: "blow", answer: "blown",translation: "aqui va"))
        verbsList.append(Verbs(verb: "broadcast", answer: "broadcast",translation: "aqui va"))
        verbsList.append(Verbs(verb: "burn", answer: "burnt",translation: "aqui va"))
        verbsList.append(Verbs(verb: "buy", answer: "bought",translation: "aqui va"))
        verbsList.append(Verbs(verb: "become", answer: "become",translation: "aqui va"))
        verbsList.append(Verbs(verb: "begin", answer: "begun",translation: "aqui va"))
        verbsList.append(Verbs(verb: "break", answer: "broken",translation: "aqui va"))
        verbsList.append(Verbs(verb: "bring", answer: "brought",translation: "aqui va"))
        verbsList.append(Verbs(verb: "build", answer: "built",translation: "aqui va"))
        verbsList.append(Verbs(verb: "catch", answer: "caught",translation: "aqui va"))
        verbsList.append(Verbs(verb: "choose", answer: "chosen",translation: "aqui va"))
        verbsList.append(Verbs(verb: "come", answer: "come",translation: "aqui va"))
        verbsList.append(Verbs(verb: "cost", answer: "cost",translation: "aqui va"))
        verbsList.append(Verbs(verb: "cut", answer: "cut",translation: "aqui va"))
        verbsList.append(Verbs(verb: "do", answer: "done",translation: "aqui va"))
        verbsList.append(Verbs(verb: "do", answer: "done",translation: "aqui va"))
        verbsList.append(Verbs(verb: "draw", answer: "drawn",translation: "aqui va"))
        verbsList.append(Verbs(verb: "dream", answer: "dreamt",translation: "aqui va"))
        verbsList.append(Verbs(verb: "drink", answer: "drunk",translation: "aqui va"))
        verbsList.append(Verbs(verb: "drive", answer: "driven",translation: "aqui va"))
        verbsList.append(Verbs(verb: "dye", answer: "dyed",translation: "aqui va"))
        verbsList.append(Verbs(verb: "eat", answer: "eaten",translation: "aqui va"))
        verbsList.append(Verbs(verb: "fall", answer: "fallen",translation: "aqui va"))
        verbsList.append(Verbs(verb: "feed", answer: "fed",translation: "aqui va"))
        verbsList.append(Verbs(verb: "fight", answer: "fought",translation: "aqui va"))
        verbsList.append(Verbs(verb: "find", answer: "found",translation: "aqui va"))
        verbsList.append(Verbs(verb: "fly", answer: "flown",translation: "aqui va"))
        verbsList.append(Verbs(verb: "forget", answer: "forgotten",translation: "aqui va"))
        verbsList.append(Verbs(verb: "freeze", answer: "frozen",translation: "aqui va"))
        verbsList.append(Verbs(verb: "get", answer: "got",translation: "aqui va"))
        verbsList.append(Verbs(verb: "give", answer: "given",translation: "aqui va"))
        verbsList.append(Verbs(verb: "go", answer: "gone",translation: "aqui va"))
        verbsList.append(Verbs(verb: "grow", answer: "grown",translation: "aqui va"))
        verbsList.append(Verbs(verb: "hang", answer: "hung",translation: "aqui va"))
        verbsList.append(Verbs(verb: "have", answer: "had",translation: "aqui va"))
        verbsList.append(Verbs(verb: "hear", answer: "heard",translation: "aqui va"))
        verbsList.append(Verbs(verb: "hide", answer: "hidden",translation: "aqui va"))
        verbsList.append(Verbs(verb: "hit", answer: "hit",translation: "aqui va"))
        verbsList.append(Verbs(verb: "hold", answer: "held",translation: "aqui va"))
        verbsList.append(Verbs(verb: "hurt", answer: "hurt",translation: "aqui va"))
        verbsList.append(Verbs(verb: "keep", answer: "kept",translation: "aqui va"))
        verbsList.append(Verbs(verb: "extinguish", answer: "extinguished",translation: "aqui va"))*/
    }
}
/*
 struct QuestionBank {
 var questionList = [Questions]()
 init() {
 questionList.append(Questions(questionText: "Have you --- for your uncle?", posibbleAnswer: "worked", answer: true))
 */
